### PR TITLE
feat: Add additionalLabels support for Pod and Service Monitors

### PR DESCRIPTION
**Pull request by VLZZZ**
This MR adds:
- Optional `.serviceMonitor.additionalLabels`
- Optional `.podMonitor.additionalLabels`

`additionalLabels` provides an ability to properly discover Monitors using the `serviceMonitorSelector.matchLabels `and `podMonitorSelector.matchLabels` with the `prometheus-operator`

### CODE REVIEW

**Comment by djeebus** [comment]
Looks good, thanks for the PR! Two things: 
1. Can you get the DCO signed? 
2. Can you add some helm tests showing that it works as expected both with and without labels?

**Comment by VLZZZ** [comment]
@djeebus Sorry for the force-push mess here, it's been a while since my last contribution, had hard times with the DCO 😄.  
I've added unit tests and also added a brief readme section on this `unittest` plugin.

**Comment by VLZZZ** [comment]
Hi @djeebus
Any updates on this so far?
Do you want me to reabase the brach to get it merged?

**Review by djeebus — DISMISSED** [review]

**Comment by djeebus** [comment]
looks good! don't think we need a rebase, but we do need you to bump the helm chart version. once that happens, lgtm!

**Comment by VLZZZ** [comment]
I've decided to bump it to the 0.6.0

**Review by djeebus — APPROVED** [review]

**Pull request merged**
