### PR TITLE
feat: Add helm chart value to render tolerations in the controller

### PR DESCRIPTION
**Pull request by Linutux42**
This PR simply adds the possibility to configure tolerations on the controller from the helm chart.

Let me know if I missed something :)

### CODE REVIEW

**Comment by mplachter** [comment]
Hi @Linutux42,

Sorry for the delay. I just need you to sign your commit so we can get this merged :)

**Comment by Linutux42** [comment]
Hey @mplachter,

done ;)

**Comment by mplachter** [comment]
I checked CI for Errors looks like these are still pending

* Bump Chart Version (minor bump would be good)
  *  to 0.5.3
 * DCO https://github.com/apps/dco

**Comment by Linutux42** [comment]
Is it better now ?

**Review by djeebus — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
