### PR TITLE
Bump golang to 1.21.3 and alpine to 3.18

### PR DESCRIPTION
**Pull request by neiljain**
- update versions in earthfile

### CODE REVIEW

**Comment by djeebus** [comment]
I believe you're going to have to bump the golang version in [.tool-versions](https://github.com/zapier/prom-aggregation-gateway/blob/main/.tool-versions#L3)

**Comment by djeebus** [comment]
While you're upgrading the world, you could swap from `quintush/helm-unittest` to `helm-unittest/helm-unittest`, which would let you upgrade it to `0.3.5`

**Comment by neiljain** [comment]
I've instead reverted helm chart related changes to focus this PR only on golang and alpine updates.  Best to look into helm chart unit testing related upgrade separately.

**Comment by djeebus** [comment]
> I've instead reverted helm chart related changes to focus this PR only on golang and alpine updates. Best to look into helm chart unit testing related upgrade separately.

good call. I approved the run,ets see how it goes!

**Comment by djeebus** [comment]
Success, thanks!

**Review by djeebus — APPROVED** [review]

**Pull request merged**
